### ISSUE TITLE
Issue in download file

### ISSUE THREAD

**Issue by anacarolinafxavier19** [hllauca/RClimChange#1]
I tried to execute the example code in download function, didnt work. 
Message error:

Downloading BCC-CSM2-MR (1/1) for 1990 (1/1)
trying URL 'https://ds.nccs.nasa.gov/thredds/fileServer/AMES/NEX/GDDP-CMIP6/BCC-CSM2-MR/historical/r1i1p1f1/pr/pr_day_BCC-CSM2-MR_historical_r1i1p1f1_gn_1990.nc'
 length 171075225 bytes (163.2 MB)
downloaded 109.7 MB

Error in download.file(url = url, destfile = tempfile, method = method) : 
  download from 'https://ds.nccs.nasa.gov/thredds/fileServer/AMES/NEX/GDDP-CMIP6/BCC-CSM2-MR/historical/r1i1p1f1/pr/pr_day_BCC-CSM2-MR_historical_r1i1p1f1_gn_1990.nc' failed
In addition: Warning messages:
1: In download.file(url = url, destfile = tempfile, method = method) :
  downloaded length 115017936 != reported length 171075225
2: In download.file(url = url, destfile = tempfile, method = method) :
  URL 'https://ds.nccs.nasa.gov/thredds/fileServer/AMES/NEX/GDDP-CMIP6/BCC-CSM2-MR/historical/r1i1p1f1/pr/pr_day_BCC-CSM2-MR_historical_r1i1p1f1_gn_1990.nc': Timeout of 60 seconds was reached
Done!
60.03 sec elapsed

**Comment by hllauca** [comment]
It seems to be a problem with your internet connection because the download is interrupted at 109.7 MB, the code is ok for many users. Please try to change the download "method".

<img width="1162" alt="Captura de Pantalla 2022-03-09 a la(s) 11 23 06" src="https://user-images.githubusercontent.com/9383944/157484657-e8591969-5901-4db0-a56b-59d64f7051bc.png">

**Comment by hllauca** [comment]
For Windows users, I recommend the "curl" method to avoid this issue.

**Comment by anacarolinafxavier19** [comment]
Thank you! The method "curl" works here.
